---
device: 'cuda:0'
seed: 42
env_name: "calvin"

logging:
  experiment_name: "mcil_calvin_evaluation_calvin"
  mode: online
  project: play_segmentation
  tags: ["MCIL","CALVIN","Evaluation"]
  vis_directory: ../visualizations

data:
  dataset_directory: "../datasets/calvin/task_D_D"
  task_embeddings: False
  evaluation:
    random_robot_state: False
    num_eval_sequences: 1000
    n_videos_to_record: 5

trainer:
  model:
    action_dim: 7
  vlm:
    name: "RN50"
    download_root: "../model_store/clip_models" 
  load:
    experiment_name: "mcil_evaluation_calvin"
    run_id: "1"
